name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.STAGING_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -H 35.208.85.237 >> $HOME/.ssh/known_hosts


      - name: Deploy to Server
        run: |
          ssh isham@35.208.85.237 "cd /home/isham/selenium && git pull origin main"
