name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p $HOME/.ssh
          echo "-----BEGIN OPENSSH PRIVATE KEY-----" > $HOME/.ssh/my_workflow_key
          echo "$SSH_PRIVATE_KEY" >> $HOME/.ssh/my_workflow_key
          echo "-----END OPENSSH PRIVATE KEY-----" >> $HOME/.ssh/my_workflow_key
          chmod 600 $HOME/.ssh/my_workflow_key
          ssh-keyscan -H 35.208.85.237 >> $HOME/.ssh/known_hosts
          eval $(ssh-agent -s)
          ssh-add $HOME/.ssh/my_workflow_key

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -v -i $HOME/.ssh/id_rsa isham@35.208.85.237 "cd /home/isham/selenium && git pull origin main"
      # Add any other steps you need for your deployment process here
