name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p $HOME/.ssh
          ssh-keyscan -H 35.208.85.237 >> $HOME/.ssh/known_hosts
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | ssh-add -

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa isham@35.208.85.237 "cd /home/isham/hr_chatbot_server && git pull origin main"

      # Add any other steps you need for your deployment process here
